name: Build

on:
  push:
    branches: [main, master, linux]
    tags: ['v*']
  pull_request:
    branches: [main, master]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

permissions:
  packages: write
  contents: write

jobs:
  build-linux:
    strategy:
      matrix:
          # tag: [alpine, latest]
          # platform: [linux/amd64, linux/arm64]
          tag: [alpine]
          platform: [linux/arm64]
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -c "docker exec -i rust sh < {0}"
    steps:
      - uses: actions/checkout@v6

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v4
        with:
          platforms: arm64
        
      - name: Start Docker Container
        shell: bash
        run: |
          docker run \
            -d \
            --name rust \
            --platform ${{ matrix.platform }} \
            -v $HOME/.cargo:/usr/local/cargo \
            -v ${{ github.workspace }}:${{ github.workspace }} \
            -w ${{ github.workspace }} \
            "docker.io/library/rust:${{ matrix.tag }}" \
            tail -f /dev/null

      - name: Setup Rust
        if: false
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache-all-crates: true
          rustflags: ""

      - name: Install dependencies
        # run: sudo apt-get install --no-install-recommends -y libtesseract-dev imagemagick tesseract-ocr-eng fonts-liberation2
        run: |
          wget --secure-protocol=TLSv1_3 -q $GORELEASER_URL
          ${{ matrix.tag == 'alpine' && 'apk add --no-cache --allow-untrusted leptonica-dev ./goreleaser*.apk'}}
          ${{ matrix.tag == 'latest' && 'sudo dpkg -i goreleaser*.deb && \
          sudo apt-get update && \
          sudo apt-get install -y libleptonica-dev' }}
        env:
          GORELEASER_URL: >-
            https://github.com/goreleaser/goreleaser/releases/download/v2.14.1/
            goreleaser_2.14.1_${{ matrix.platform == 'linux/amd64' && 'amd64' || 'arm64' }}
            ${{ matrix.tag == 'alpine' && '.apk' || '.deb' }}

      - name: build
        run: cargo build --release --locked --features bundled

  build-windows:
    runs-on: windows-2025-vs2026
    if: false
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      
      - name: Setup MSVC
        uses: TheMrMilchmann/setup-msvc-dev@v4
        with:
          arch: x64
      
      - name: Get env
        run: |
          echo "VCPKG_INSTALLATION_ROOT=$env:VCPKG_INSTALLATION_ROOT" >> $env:GITHUB_ENV
      
      - name: Restore cache
        id: cache-restore
        uses: actions/cache/restore@v5
        with:
          path: |
            ${{env.VCPKG_INSTALLATION_ROOT}}\packages
            ${{env.VCPKG_INSTALLATION_ROOT}}\installed
          key: ${{ runner.os }}-vcpkg-2026-03-06
      
      - name: Install leptonica
        if: steps.cache-restore.outputs.cache-hit != 'true'
        run: |
          $env:VCPKG_ROOT = $env:VCPKG_INSTALLATION_ROOT
          vcpkg install leptonica:x64-windows-static
      
      - name: Save to cache
        if: steps.cache-restore.outputs.cache-hit != 'true'
        uses: actions/cache/save@v5
        with:
          path: |
            ${{env.VCPKG_INSTALLATION_ROOT}}\packages
            ${{env.VCPKG_INSTALLATION_ROOT}}\installed
          key: ${{ steps.cache-restore.outputs.cache-primary-key }}

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: x86_64-pc-windows-msvc
          rustflags: ""
          cache-all-crates: true
      
      - name: Build
        run: |
          $env:VCPKG_ROOT = $env:VCPKG_INSTALLATION_ROOT
          cargo build --release --locked --features bundled 
        env:
          RUSTFLAGS: "-C target-feature=+crt-static"
          VCPKGRS_TRIPLET: "x64-windows-static"
          TESSDATA_PREFIX: ".\tessdata"
        
      - name: Download language data
        run: |
          mkdir tessdata
          $baseUrl = "https://github.com/tesseract-ocr/tessdata/raw/main"
          @("eng", "osd") | ForEach-Object {
            Invoke-WebRequest -Uri "$baseUrl/$_.traineddata" -OutFile "tessdata/$_.traineddata"
          }
      
      - name: Package
        run: |
          $packageDir = "ocrlocate"
          mkdir $packageDir
          Copy-Item "target\release\ocrlocate.exe" $packageDir
          Copy-Item "tessdata" "$packageDir\tessdata" -Recurse
          Compress-Archive -Path $packageDir -DestinationPath "ocrlocate-x86_64-pc-windows-msvc.zip"
      
      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: ocrlocate-windows
          path: ocrlocate-x86_64-pc-windows-msvc.zip
          archive: false
      
      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: ocrlocate-x86_64-pc-windows-msvc.zip
