name: Windows Build

on:
  push:
    branches: [main, master]
    tags: ['v*']
  pull_request:
    branches: [main, master]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  # USERNAME: ${{ github.repository_owner }}
  # FEED_URL: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
  # VCPKG_BINARY_SOURCES: "clear;nuget,https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json,readwrite"

permissions:
  packages: write

jobs:
  build-windows:
    runs-on: windows-2025-vs2026
    
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      
      - name: Setup MSVC
        uses: TheMrMilchmann/setup-msvc-dev@v4
        with:
          arch: x64
      
      - name: Get env
        run: |
          echo "VCPKG_INSTALLATION_ROOT=$env:VCPKG_INSTALLATION_ROOT" >> $env:GITHUB_ENV
      
      - name: Restore cache
        id: cache-restore
        uses: actions/cache/restore@v5
        with:
          path: ${{env.VCPKG_INSTALLATION_ROOT}}\packages
          key: ${{ runner.os }}-vcpkg
      
      - name: Install leptonica
        if: steps.cache-restore.outputs.cache-hit != 'true'
        run: |
          vcpkg install leptonica:x64-windows-static
      
      - name: Save to cache
        if: steps.cache-restore.outputs.cache-hit != 'true'
        uses: actions/cache/save@v5
        with:
          path: ${{env.VCPKG_INSTALLATION_ROOT}}\packages
          key: ${{ steps.cache-restore.outputs.cache-primary-key }}

      # - name: Setup vcpkg
      #   uses: lukka/run-vcpkg@v11
      #   with:
      #     vcpkgDirectory: ${{ github.workspace }}/vcpkg
      #     vcpkgGitCommitId: 62159a45e18f3a9ac0548628dcaf74fcb60c6ff9
      #     vcpkgJsonGlob: "vcpkg.json"
      #     runVcpkgInstall: true
      #     doNotCache: false
      #   env:
      #     VCPKG_DEFAULT_TRIPLET: "x64-windows-static"
      
      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          target: x86_64-pc-windows-msvc
      
      - name: Debug env
        run: |
          echo "VCPKG_ROOT: $env:VCPKG_INSTALLATION_ROOT"
          echo "PATH: $env:PATH"
          echo "GITHUB_WORKSPACE: $env:GITHUB_WORKSPACE"
          ls $env:VCPKG_INSTALLATION_ROOT/packages/
      
      - name: Probe leptonica
        run: |
          cd $RUNNER_TEMP
          git clone https://github.com/mcgoo/vcpkg-rs.git
          cd vcpkg-rs
          cargo install --path ./vcpkg_cli
          vcpkg_cli probe -l static leptonica
      
      - name: Build
        run: |
          $env:VCPKG_ROOT = $env:VCPKG_INSTALLATION_ROOT
          cargo build --release --locked --features bundled
        env:
          RUSTFLAGS: "-C target-feature=+crt-static"
      
      - name: Download language data
        run: |
          mkdir tessdata
          $baseUrl = "https://github.com/tesseract-ocr/tessdata/raw/main"
          @("eng", "osd") | ForEach-Object {
            Invoke-WebRequest -Uri "$baseUrl/$_.traineddata" -OutFile "tessdata/$_.traineddata"
          }
      
      - name: Package
        run: |
          $packageDir = "ocrlocate"
          mkdir $packageDir
          Copy-Item "target\release\ocrlocate.exe" $packageDir
          Copy-Item "tessdata" "$packageDir\tessdata" -Recurse
          Compress-Archive -Path $packageDir -DestinationPath "ocrlocate-x86_64-pc-windows-msvc.zip"
      
      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: ocrlocate-windows
          path: ocrlocate-x86_64-pc-windows-msvc.zip
      
      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: ocrlocate-x86_64-pc-windows-msvc.zip
